# ?? (Optional) Make the tiling feel closer to BSP/i3 ???????????????????????????
# Disables auto-flattening & forced alternating orientations.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# ?? Main (Hyper = cmd+alt+ctrl+shift) ?????????????????????????????????????????
[mode.main.binding]
# Core
cmd-alt-ctrl-shift-q = "close"
cmd-alt-ctrl-shift-f = "fullscreen"          # explicit ON (OFF lives in a mode)
cmd-alt-ctrl-shift-g = "layout floating"        # quick toggle float<->tile

# Focus (hjkl)
cmd-alt-ctrl-shift-h = "focus --boundaries-action wrap-around-the-workspace left"
cmd-alt-ctrl-shift-j = "focus --boundaries-action wrap-around-the-workspace down"
cmd-alt-ctrl-shift-k = "focus --boundaries-action wrap-around-the-workspace up"
cmd-alt-ctrl-shift-l = "focus --boundaries-action wrap-around-the-workspace right"

# Workspaces 1..10 + back-and-forth
cmd-alt-ctrl-shift-1 = "workspace 1"
cmd-alt-ctrl-shift-2 = "workspace 2"
cmd-alt-ctrl-shift-3 = "workspace 3"
cmd-alt-ctrl-shift-4 = "workspace 4"
cmd-alt-ctrl-shift-5 = "workspace 5"
cmd-alt-ctrl-shift-6 = "workspace 6"
cmd-alt-ctrl-shift-7 = "workspace 7"
cmd-alt-ctrl-shift-8 = "workspace 8"
cmd-alt-ctrl-shift-9 = "workspace 9"
cmd-alt-ctrl-shift-0 = "workspace 10"

# Move screen to other monitor
cmd-alt-ctrl-shift-tab   = "move-workspace-to-monitor --wrap-around next"

ctrl-alt-1 = "move-node-to-workspace 1"
ctrl-alt-2 = "move-node-to-workspace 2"
ctrl-alt-3 = "move-node-to-workspace 3"
ctrl-alt-4 = "move-node-to-workspace 4"
ctrl-alt-5 = "move-node-to-workspace 5"
ctrl-alt-6 = "move-node-to-workspace 6"
ctrl-alt-7 = "move-node-to-workspace 7"
ctrl-alt-8 = "move-node-to-workspace 8"
ctrl-alt-9 = "move-node-to-workspace 9"
ctrl-alt-0 = "move-node-to-workspace 10"

# Mode switches (single Hyper, no extra mods)
cmd-alt-ctrl-shift-r = "mode resize"
cmd-alt-ctrl-shift-m = "mode move"

# ?? Resize mode (no modifiers)
[mode.resize.binding]
h = "resize smart -70"
j = "resize smart +70"
k = "resize smart -70"
l = "resize smart +70"

enter = "mode main"
esc   = "mode main"
r     = "mode main"

# ?? Move mode (replaces your old alt-ctrl-h/j/k/l) ????????????????????????????
[mode.move.binding]
h = "move left"
j = "move down"
k = "move up"
l = "move right"

x = "join-with left"

enter = "mode main"
esc   = "mode main"
m     = "mode main"

[[on-window-detected]]
if.window-title-regex-substring = "Picture-in-Picture"
run = "layout floating"

[[on-window-detected]]
if.app-id = "com.apple.systempreferences"
run = "layout floating"
