#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

# Set up monitors
bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-A-1 -d 10

# Set DP-1 as primary monitor
xrandr --output DP-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal \
       --output HDMI-A-1 --mode 1920x1200 --pos 3840x0 --rotate left

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start picom
picom --config ~/.config/picom/picom-minimal.conf &

# Sleep for a bit to let picom start
sleep 1

# Start other applications
~/.config/polybar/launch.sh
feh --bg-scale ~/wallpaper.png
dunst &
