#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

autorandr -c

if xrandr --query | grep -q "^HDMI-0 connected"; then
    primary_monitor="HDMI-0"
    # Remove DP-0 if HDMI-0 is connected
    if xrandr --query | grep -q "^DP-0 connected"; then
        bspc monitor DP-0 -r
        xrandr --output DP-0 --off
    fi
elif xrandr --query | grep -q "^DP-0 connected"; then
    primary_monitor="DP-0"
else
    primary_monitor=$(xrandr --query | grep " connected" | head -n 1 | cut -d' ' -f1) # Fallback to the first connected
fi

bspc monitor $primary_monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Start picom
picom --config ~/.config/picom/picom.conf &

# Sleep for a bit to let picom start
sleep 1

# Start other applications
~/.config/polybar/launch.sh --blocks
feh --bg-scale ~/wallpaper.png
dunst &
