[main]
font=JetBrainsMono Nerd Font Mono:size=11
dpi-aware=no

[colors-dark]
foreground=dcd7ba
background=1f1f28

## Normal colors
regular0=16161d
regular1=c34043
regular2=76946a
regular3=c0a36e
regular4=7e9cd8
regular5=957fb8
regular6=6a9589
regular7=c8c093

## Bright colors
bright0=727169
bright1=e82424
bright2=98bb6c
bright3=e6c384
bright4=7fb4ca
bright5=938aa9
bright6=7aa89f
bright7=dcd7ba
